### ISSUE TITLE
Won't return to "view" state after updating a resource

### ISSUE THREAD

**Issue by renyuneyun** [SolidOS/source-pane#43]
I'm using CSS with [Mashlib Recipe](https://github.com/CommunitySolidServer/Recipes).

When modifying resources (e.g. turtle file), the first modification works without issues.
However, the page is still on the "modify" state, and I can change the content of resource. In this case, after changing and submitting change, it will give me
```
Error saving back: Error: Web error: 412 (Precondition Failed) on PUT of <PATH_TO_RESOURCE>
```

But I noticed that in fact the state should be changed to "view" state rather than "modify" state, which is the behaviour on NSS. I can manually click the cross icon, and it will return to "view" state. But this should be automatically done.

**Comment by bourgeoa** [comment]
There are in fact different issues here : 
- I think NSS do not implement `if-match` and 412 error
- mashlib source-pane do not update `ETag` after a PUT

The actual work flow is to stay in `edit` mode after a `save`. Getting out of `edit` mode is done with `cancel` button "X"

**Comment by TallTed** [comment]
> The actual work flow is to stay in edit mode after a save. Getting out of edit mode is done with cancel button "X"

In this case, the SAVE should dim immediately after a save, as there are no longer any changes to save.

I confess, I don't understand why the flow is to stay in EDIT mode after a SAVE. I don't think this flow matches any desktop app I use, and few if any web apps. Where did it come from?
